### PR TITLE
update the readme to have some more guidelines

### LINKED ISSUE #70: Provide Set-up the project guidelines in Readme
We currently do not have any guidelines regarding setting up the project in their local system for the people who come to the project with the motive of contributing. Therefore, adding one would help them to understand the project requirements and how to set up the project for contributing.
Formally, we should update the Readme.md file to have some more guidelines.

I am working on this and will soon open a PR to address this :)

### PR DESCRIPTION
**Pull request by Grumpyyash**
Updated the readme file to have some more guidelines on how to set the project up and some general technical jargons regarding the project.
This PR resolves #70

### CODE REVIEW

**Comment by Grumpyyash** [comment]
I would request the community @wdevon99 @charithccmc @ffalpha to have a look at this and suggest changes if any :)

**Review by pranay-simejia — COMMENTED** [review]
i think you should update [Gatsby](https://www.gatsbyjs.com/docs/quick-start) **to**  [Gatsby CLI link](https://www.gatsbyjs.com/docs/reference/gatsby-cli/). 

Great work, though!

**Review by wdevon99 — APPROVED** [review]

**Comment by garvitchittora** [comment]
@Grumpyyash Hi bro, I was trying to setup Webiu but getting this error again and again. Can you please help in fixing this?

Screenshot from 2021-03-11 18-46-22

**Comment by Grumpyyash** [comment]
Hi @garvitchittora I think you should join the respective gitter channel of the project available on https://scorelab.org/ and ask for help as many other contributors also had this doubt I guess so you would get answers from those who encountered and solved this issue. 
Happy contributing :)

**Comment by Grumpyyash** [comment]
I would request @charithccmc sir to please review this as @wdevon99 sir has approved it :)

**Comment by Grumpyyash** [comment]
Already done in #169

**Pull request closed without merging**
