### PR TITLE
Initialize storybook for documentation of the components

### LINKED ISSUE #65: Documentation of components using Storybook
Storybook is a really powerful tool to build and document reusable components. It gives the flexibility of rendering, checking the UI, responsiveness and thus, it would be really beneficial for our project where we need to see how our reusable component looks like.
I am working on this and will soon open a PR for the same

### PR DESCRIPTION
**Pull request by Grumpyyash**
This PR resolves #65 
Initialized the storybook in the project for the documentation and UI rendering of the components.
Storybook is a really helpful tool to preview and document reusable components. I have currently added the boilerplate for the same in this PR and have created stories for the footer, button, contact and navbar components and will add others simultaneously as well.
Currently added stories - 
Footer, Button with Heading, Contact, Navbar, Page-not-found, Team component

button

footer

Navbar

contact

### CODE REVIEW

**Comment by Grumpyyash** [comment]
@wdevon99 @charithccmc could you please review this PR so that I can add stories for other components as well if you permit?

**Comment by Grumpyyash** [comment]
I have added args as well which could be used as props to pass data

**Comment by ffalpha** [comment]
Hi @Grumpyyash I have added storybook documentation for all the components. Even the Initialize storybook part was done 2 weeks ago. So this will be duplicate. It will be waste of time for you. You can try something else or can review my code. You can checkout  #it here ( #38 )  :)

**Comment by Grumpyyash** [comment]
Thank you so much for telling me this. I didn't see that PR :)

**Comment by Grumpyyash** [comment]
Yes, I will be happy to review you code :)

**Review by wdevon99 — APPROVED** [review]
LGTM

**Pull request closed without merging**
