### PR TITLE
created a component to show contributers to a github project

### LINKED ISSUE #20: Create a component to show the list of contributors to a Github project
# Goal

Create a component to show the list of contributors to a specific Github project.
**Note**: Using Github API is suggested

### PR DESCRIPTION
**Pull request by Grumpyyash**
This PR fixes #20 
Created a custom component to show the list of contributers to a particular github project using github APIs. The project whose list is needed can simply be passed as a prop to the component and it will fetch and render all the data.

contributers-bassa
contributers-webiu

### CODE REVIEW

**Comment by Grumpyyash** [comment]
@wdevon99  @charithccmc  could you please this PR?

**Review by wdevon99 — CHANGES_REQUESTED** [review]
Incorrect SASS syntax, shouldn't have "{" and ";"

**Comment by Grumpyyash** [comment]
SASS also supports vanilla css styling I guess. However, I will just update it. 
Thanks for reviewing @wdevon99

**Comment by Grumpyyash** [comment]
@wdevon99 I have updated the correct syntax, would you please review it now?

**Review by wdevon99 — APPROVED** [review]
LGTM

**Comment by Grumpyyash** [comment]
Already done in the GitHub APIs PR :)

**Pull request closed without merging**
