### PR TITLE
add the search functionality to projects list component

### LINKED ISSUE #22: Create a reusable Search Bar Component
# Goal

Create a reusable Search Bar Component. 
**Note:** This should be a generic Search Bar which can be customized via props.

### LINKED ISSUE #23: Add the search functionality to the Project List Component
# Goal

Use the Reusable Search Bar Component to add the search functionality to the Project List Component.
**Note:** Before Starting this issue, #22 issue should be completed.

### PR DESCRIPTION
**Pull request by Grumpyyash**
This PR fixes #22 and also resolves #23 
Created the functionality of searching projects from the list using project name and rendering accordingly. Also, a new search bar component which can be used as needed for other functions as well. The 'items' array is a prop which is to be populated with all the projects information while rendering this component and it will function well.

search-projects

half-search

full-search

### CODE REVIEW

**Comment by Grumpyyash** [comment]
@wdevon99  @charithccmc  could you please review this PR?

**Review by wdevon99 — CHANGES_REQUESTED** [review]
The search bar should be a separated reusable component

**Comment by Grumpyyash** [comment]
@wdevon I have separated the search bar to be another component. Please also review #61 to see only the search component and this PR integrates the functionality to the projects lists also. Could you please review this PR?

**Comment by Grumpyyash** [comment]
Already done in #178

**Pull request closed without merging**
