### PR TITLE
create a reusable FAQ component

### LINKED ISSUE #35: Create a reusable 'FAQ' kind of component
Many organizational websites often require an faq kind-of section to give insights and clarify common questions regarding their services, It would be a good idea if we are able to implement a reusable component which can be customized by passing data through props.
Formally, we want to achieve something like this

FAQs

Any suggestions and discussions are welcome from the community @wdevon99 @charithccmc .
I am working on this and expected to open a PR soon.

### PR DESCRIPTION
**Pull request by Grumpyyash**
This PR resolves #35 
Created a reusable and highly customizable FAQ component which would speed up getting a website up and running. The data to be displayed needs to be passed as a prop to the component like this - 

faq-code

The stylesheet has been updated to do custom styling if required, the component formally looks like this, with a lot of flexibility possible

faq

### CODE REVIEW

**Comment by Grumpyyash** [comment]
Could you please review this? @wdevon99 @charithccmc any suggestions or features to be added from the community would be appreciated

**Review by wdevon99 — CHANGES_REQUESTED** [review]
This component is just a wrapper for "react-faq-component" lib component so better build it from scratch and remove the dependact

**Comment by Grumpyyash** [comment]
@wdevon99 I have tried to build the entire component from scratch and have deleted any other dependencies. Would you please review it now?

FAQ

**Review by wdevon99 — APPROVED** [review]
LGTM

**Comment by Grumpyyash** [comment]
Will improve in fresh PR :)

**Pull request closed without merging**
