### PR TITLE
update "links" component to include an icon

### LINKED ISSUE #21: Improve the "Links" Component to make it possible to include an icon for the link
# Goal

Improve the "Links" Component to make it possible to include an icon for the link

**Screenshot of current Link Component**

Screenshot 2020-10-11 at 11 42 12

### PR DESCRIPTION
**Pull request by Grumpyyash**
This PR fixes #21 
As desired, the icon visibility can be passed as a prop to the the component and if users wishes he can render icons with links as well and also he can choose to not show the icon.
links

### CODE REVIEW

**Comment by Grumpyyash** [comment]
@wdevon99 @charithccmc , could you please review this PR?

**Review by wdevon99 — CHANGES_REQUESTED** [review]
The icons should come before the link and should be able to change the icons via props

**Comment by Grumpyyash** [comment]
Thanks, @wdevon99 will update it soon

**Comment by Grumpyyash** [comment]
@wdevon99 I have updated the icon to come before the link and the icon is prop controlled as well. We can pass props to the component to decide if we want to render it or not. Could you please review it now?

**Comment by Grumpyyash** [comment]
Already covered in #173

**Pull request closed without merging**
