### PR TITLE
Blog grid component

### PR DESCRIPTION
**Pull request by Sapnajha19**
## Description
Created a BlogGrid component for the fifth theme with responsive design.

## Related Issue

#416

## Screenshots (In case of UI changes):

Desktop
localhost_8000 - Google Chrome 18-03-2023 13_58_37

Mobile
mobile

Tablet
mobile (1)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests have passed and it does not give any unexpected error for the same.

### CODE REVIEW

**Comment by dhruv18ranjan** [comment]
Hey .. Actually I already did that !

**Comment by Sapnajha19** [comment]
> Hey .. Actually I already did that !

Oh I see, Actually I saw the issue opened that's why I created the pull request. Sorry for the confusion.

**Comment by dhruv18ranjan** [comment]
> Oh I see, Actually I saw the issue opened that's why I created the pull request. Sorry for the confusion.

No problem

**Comment by Sapnajha19** [comment]
> > Oh I see, Actually I saw the issue opened that's why I created the pull request. Sorry for the confusion.
> 
> No problem

Hey, so should I close this pull request then? Actually, I made this to understand the codebase and git workflow. But there are some problems with this pr so I am thinking of creating a new pull request for the same issue. Are you okay with me creating a new one or should I close this one and not create a new pr for the same issue?

**Comment by dhruv18ranjan** [comment]
Yeah I see now there is some issue in this PR . I think you should create a new pr for another issue as 2 pr for the same issue  can create conflicts .

**Comment by Sapnajha19** [comment]
Okay, Thank you

**Pull request closed without merging**
