### PR TITLE
Issue24 add logo

### PR DESCRIPTION
**Pull request by sachinsom93**
# RESOLVES: ISSUE #24
Designed and Added a logo, which could be used in Readme.md and Documentation of Webiu.

### ScreenShot of Logo
Webiu

@wdevon99 ,Could you please review this ? I would love to get suggestions from the community.

### CODE REVIEW

**Comment by sachinsom93** [comment]
Could you please review this ? @wdevon99

**Comment by wdevon99** [comment]
@sachinsom93 How does this logo represent the purpose of Webiu?  :)

**Comment by sachinsom93** [comment]
Hi @wdevon99, thanks for feedback, the basic idea thought behind this is "create faster websites".

**Comment by sachinsom93** [comment]
Should I go for designing other style of logo ?

**Comment by Grumpyyash** [comment]
A logo was selected and added in PR #182. Thanks for your contribution @sachinsom93 :)

**Pull request closed without merging**
