### PR TITLE
Add Storybook documentation for all the existing components

### LINKED ISSUE #39: Create Documentation for existing components using https://storybook.js.org
Storybook is an open source tool for developing UI components in isolation .It allows you to browse a component library, view the different states of each component, and interactively develop and test components. Adding Documentation for existing components using Storybook will help for future developers Currently Webui doesn't have proper documentation for existing components

### PR DESCRIPTION
**Pull request by ffalpha**
Fixes   #39 
**Commit Summary** 
- I have added storybook documentation  for all the existing components 
-  Everything is sorted in alphabetical order
- Props can be changed via controls 
- 

@charithccmc @wdevon99  Can you give a feedback regarding this ?

### CODE REVIEW

**Review by wdevon99 — CHANGES_REQUESTED** [review]
Please revert the white space and formatting changes :)

**Comment by ffalpha** [comment]
Will do @wdevon99

**Comment by ffalpha** [comment]
@wdevon99 How about now ?

**Comment by ffalpha** [comment]
I have added storybook documentation for all the existing components .@wdevon99 @charithccmc could you please review this PR  ?

**Comment by Grumpyyash** [comment]
Nice work @ffalpha !

**Review by Grumpyyash — COMMENTED** [review]
One thing I would like to suggest in 'Footer.stories.js' that once you have declared a global const 'socialLinksarray' already, then you can simply put {socialLinks: socialLinksarray} while passing to 'footer.args' I guess. It would avoid repeatability of the same code again and again

review

**Comment by Grumpyyash** [comment]
Storybook documentation for all previous and new components was added in #184. Thanks for your contribution @ffalpha :)

**Pull request closed without merging**
